image: node:12-alpine

stages:
  - test
  - build

default:
  tags:
    - docker
  before_script:
    - cd Code/frontend
    - npm ci

lint:
  stage: test
  script: 
    - npm run lint

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
