frontend:lint:
  stage: test
  needs: []
  script: 
    - cd Code/frontend
    - npm ci
    - npm run lint

frontend:test:
  stage: test
  needs: []
  script:
    - cd Code/frontend
    - npm ci
    - npm run test

frontend:build:
  stage: build
  needs: ["frontend:lint", "frontend:test"]
  script:
    - cd Code/frontend
    - npm ci
    - npm run build
