#+CALL: Setup()
#+latex_class: IEEEtran
#+latex_class_options: [conference]

* COMMENT Introduction
The paper setup controls the export of content for publication. Using a
dedicated paper setup makes it simpler to include the content later in a thesis,
simply by swapping or ignoring the setup of the individual file and using and
overarching =thesis.setup=. Additionally, for publication we can remove any
setup at all to get a clean export using whatever class provided by the
publisher. If NeuroImage is the target, for example, then we should use the
elsarticle class. Support for multiple classes for publication, within Emacs
Org-Mode, can be found [[https://github.com/jkitchin/scimax/blob/master/ox-manuscript/ox-manuscript.el][in the scimax starters package]]. To make the main file
inclusion simpler, only use the first 5 lines of the paper file for extra
configuration. All the rest should go in the setup file.

Remember that #+OPTIONS are parsed even from =:noexport:= headings.

* Options :noexport:
The options are intended to remove default clutter that Org adds automatically to the export.

#+options: date:nil ^:{} toc:nil d:t tags:nil author:nil title:nil
# #+options: title:nil author:nil num:nil


* LaTeX headers :noexport:
#+latex_header: \usepackage[T1]{fontenc}
#+latex_header: \usepackage[utf8]{inputenc}
#+latex_header: \usepackage[pdftex]{graphicx}
#+latex_header: \usepackage{hyperref}


* Frontmatter :ignore:
#+BEGIN_EXPORT latex
\author{\IEEEauthorblockN{Carlos Perez}\\
\IEEEauthorblockA{Medical Engineering - Health and Medical Data Analytics \\Friedrich-Alexander-Universität Erlangen Nürnberg, Germany\\
Email: carlos.a.perez@fau.de}\\}
#+END_EXPORT

#+LATEX: \maketitle

* Setup :noexport:
#+NAME: Setup
#+begin_src emacs-lisp :results drawer
  (add-to-list 'org-latex-classes
               '("IEEEtran"
                 "\\documentclass{IEEEtran}
 [NO-DEFAULT-PACKAGES]
 [PACKAGES]
 [EXTRA]
"
                 ("\\section{%s}"       . "\\section*{%s}")
                 ("\\subsection{%s}"    . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                ))
#+end_src
